Universe           = vanilla
concurrency_limits = CONCURRENCY_LIMIT_DEFAULT:100
initialDir         = /sphenix/user/mitrankova/analysis/K_short_new/macros 
Executable         = $(initialDir)/runKShortReco.sh
  Output  	= /sphenix/user/mitrankova/analysis/K_short_new/log/K_short_new_$(process).out
  Error         = /sphenix/user/mitrankova/analysis/K_short_new/log/K_short_new_$(process).err
  Log  	        = /sphenix/user/mitrankova/analysis/K_short_new/log/K_short_new_$(process).log
PeriodicHold       = (NumJobStarts>=1 && JobStatus == 1)
request_memory     = 6GB
Priority           = 20
job_lease_duration = 3600
Arguments          = $(inputFile)
Queue inputFile from runlist_52844_52848.txt 
